spring:
  application:
    name: spring-data-jpa-practice
    media:
      image:
        bucket: /media/image/rest
  datasource:
    url: jdbc:postgresql://localhost:5433/spring_data_jpa
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope: openid,email,profile

server:
  error:
    whitelabel:
      enabled: false